server:
  port: 9001

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://msa-order-db/msa_order
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serverUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
